=== SrWosel/juegosretro/html/xml/psx.dtd
<!ELEMENT consolas (consola)>
<!ELEMENT consola (nombre, company, anyo_jap, anyo_usa, anyo_eu, finprod, ventas, proces, formato)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT company (#PCDATA)>
<!ELEMENT anyo_jap (#PCDATA)>
<!ELEMENT anyo_usa (#PCDATA)>
<!ELEMENT anyo_eu (#PCDATA)>
<!ELEMENT finprod (#PCDATA)>
<!ELEMENT ventas (#PCDATA)>
<!ELEMENT proces (#PCDATA)>
<!ELEMENT formato (#PCDATA)>

=== SrWosel/juegosretro/html/xml/psx.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE consolas SYSTEM "file:///E:/PROYECTO/Juegos%20a%20criterio%20PROYECTO%20MARCAS/html/xml/psx.dtd">
<consolas>
<consola>


<nombre>PlayStation</nombre>
<company>Sony</company>


      <anyo_jap>3 de diciembre de 1994</anyo_jap>
      <anyo_usa>9 de septiembre de 1995</anyo_usa>
      <anyo_eu>29 de septiembre de 1995</anyo_eu>


<finprod>	23 de marzo de 2006</finprod>
<ventas>104 250 000 consolas</ventas>
<proces>R3000A a 33.8688 MHz de 32 bits</proces>
<formato>CD-ROM</formato>



</consola>
</consolas>
